### ISSUE TITLE
Enforce `squash merging`

### ISSUE THREAD

**Issue by steakhal** [luksan47/mars#113]
As we already discussed and settled with the PR merge strategies, we should enforce the chosen strategy: `squash`
Now the history is a complete mess, since there are a bunch of merge commits on the master...
![image](https://user-images.githubusercontent.com/6280485/67758667-66bba280-fa3e-11e9-9179-79d96c940037.png)

Please consider restricting the merge strategies for the master branch. I think it would increase the readability in the future.

Here is a help, [how to do it in the settings](https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests).

**Comment by luksan47** [comment]
The problem is I always use squash commits (now it's enforced for your request), but when I check the `git log` on my console, all separate commits are present.

On a side note, please restrain from using the critical tag on non-critical issues.

**Comment by luksan47** [comment]
I see what happened now, @katkodominik merged with rebase. Now makes sense the enforcing.
I'll leave this for now, probably does not worth the trouble to clean the branch. If you think otherwise, feel free to reopen this issue and re-assign to yourself.

**Comment by steakhal** [comment]
I wouldn't ever touch the history of the `master` branch. Since forks could reference the commits.
The only thing we can do is to enforce these rules on the future PRs.
