### ISSUE TITLE
Cancel print jobs

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#119]
Add an options for the users and admins to cancel the already started printing jobs. Currently there is a placeholder function doing nothing, just changing the state.

**Comment by rindy22** [comment]
Hello, i would like to work on this issue if it is still open. Please assign it on me.

**Comment by luksan47** [comment]
#130 addressed cancelling in a way, but there's still some work to be done. @uno20001 do you have any notion how to move forward there?

**Comment by uno20001** [comment]
Apart from handling the race conditions, the actual UI is what needs to implemented.

**Comment by luksan47** [comment]
Thanks @uno20001 for the clarification. @rindy22 are you okay with doing the frontend? Solving the race condition is optional.

**Comment by rindy22** [comment]
Can you give me more information about frontend? Thanks.
