### ISSUE TITLE
Create document generator

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#12]
Would be a nice feature to generate automatically the documents required by house rule and other things.

**Comment by husar** [comment]
Hello, can you give me more information about this issue? Something about house rules and type of document.

**Comment by luksan47** [comment]
We need to come up with a more developed plan for this task, until then it's on hold.

**Comment by luksan47** [comment]
@boldar99 will create the template LaTeX documents

**Comment by luksan47** [comment]
This is fixed now.
