### ISSUE TITLE
Add a user information page

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#13]
A (currently optional) page where users can fill out personal information (like in Uran 1.1), for later use. Should not be a requirement at registration.

**Comment by erko185** [comment]
Hi I can take this problem. Please write me more information where you need this page

**Comment by luksan47** [comment]
Hi, thanks!
It should be a page under username's dropdown menu.
I think the simplest solution is a big form, which should contain the following:
**Personal information**: name, email, address (zip code, city, street, etc could be separated), language, date and place of birth, mother's name, phone number.
**Information of studies:** 
Name of secondary school
Year of the leaving exam
Neptun identifier
Year of enrollment
Faculty, options are:

- Jogtudományi Kar
- Bárczi Gusztáv Gyógypedagógiai Kar
- Bölcsészettudományi Kar
- Informatikai Kar
- Pedagógiai és Pszichológiai Kar
- Tanító- és Óvóképző Kar
- Társadalomtudományi Kar
- Természettudományi Kar

Workshop, options are (multiple options possible):

- Angol-amerikai műhely
- Biológia-kémia műhely
- Bollók János Klasszika-filológia műhely
- Filozófia műhely
- Aurélien Sauvageot Francia műhely
- Germanisztika műhely
- Informatika műhely
- Magyar műhely
- Matematika-fizika műhely
- Mendöl Tibor földrajz-, föld- és környezettudományi műhely
- Olasz műhely
- Orientalisztika műhely
- Skandinavisztika műhely
- Spanyol műhely
- Szlavisztika műhely
- Társadalomtudományi műhely
- Történész műhely

**Comment by luksan47** [comment]
You can copy most of the page from here (we are rewriting this system):
https://github.com/kovacsur10/uran/blob/master/resources/views/user/showdata.blade.php

**Comment by erko185** [comment]
Okey I understand. Do you need only page or backend also

**Comment by erko185** [comment]
and please add assign in to task

**Comment by erko185** [comment]
and insert code to which brands ?

**Comment by erko185** [comment]
Mars je jednotným informačným systémom Urán 2.0 pre Eötvös Collegium.

**Comment by luksan47** [comment]
> Do you need only page or backend also

Once the page is done, updating the backend would be easy, so please add that, too.

> and insert code to which brands ?

You can create your own branch or fork the repo, then send a pull request.

**Comment by erko185** [comment]
I dont have permission for push into my new branch.Please set me permission. Thanks.

**Comment by steakhal** [comment]
You won't get permission for this repository. You should fork it, push your local branch into you fork, and create a pull request from that branch to the `luksan/master`. @erko185 

If you need assistance, feel free to reach out to me.

**Comment by erko185** [comment]
Ok. I created pull requst. PLease will you chceck form in info.blade.php. I used form because is more secury than use ajax call. When wil be good page I will create backend. I used basic css. I will use post method for write data into database after.

**Comment by luksan47** [comment]
@erko185, you created the Pull Request on your forked repository. Please navigate luksan47/mars (this repository) and open the pull request there, and set the source to your fork. You can check if it's created on this page:
https://github.com/luksan47/mars/pulls
Also, check this guide out, it describes how to open PRs from forks, just what you need:
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by erko185** [comment]
I did it according to the instructions.

**Comment by luksan47** [comment]
Thank you, left some comments there.

**Comment by erko185** [comment]
Will I create table for user information and create backend  or we give me scheme this table?

**Comment by luksan47** [comment]
We can create the backend, after you are done with the UI.

**Comment by erko185** [comment]
Form for backend is created but I don't know how to look the form.

**Comment by steakhal** [comment]
I'm not sure what going on here. Could someone sum it up?

**Comment by luksan47** [comment]
@steakhal check out #73
