### ISSUE TITLE
Node Radius server

### ISSUE THREAD

**Issue by gkrupp** [luksan47/mars#134]
Using FreeRADIUS implicates DB restrictions like table synchronization as its stated as a possible solution in #15. I advise not to meddle with existing solutions but create our own radius authentication service in Node using the existing DB structures avoiding credential synchronization (using [radius](https://www.npmjs.com/package/radius) and [mysql](https://www.npmjs.com/package/mysql) packages, furthermore, it could be perfectly managed by [pm2](https://pm2.keymetrics.io) (a production-ready process manager).

**Comment by luksan47** [comment]
[I was meant to comment here, deleted under the other issue]
@gkrupp @hamaren2517 will you have time to work in this before the next semester starts?

**Comment by gkrupp** [comment]
The code is ready but further testing and configuration required to work with the current database scheme and router settings.
