### ISSUE TITLE
Fix printer job id

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#143]
The printing failed with Error 500 when a user wanted to print. In the logs:
```
[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'REDACTED-5267' for column 'job_id' at row 1 at /va
r/www/uran/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
```
The problem is with getting the job id correctly. Now we get a string with the schema 'printern_name-job_id', but the table schema requires job id to be an integer.

I see two solutions to:

- add a migration to change the column type
- drop the printer name from the job id, as we have one printer anyway and continue using it as integer.

In production, the first workaround is used until the fix is deployed.

**Comment by steakhal** [comment]
How could such a bug slip through our hands?
Haven't we tested this functionality?

I would favor the general solution and not restrict ourselves to a single printer.

**Comment by luksan47** [comment]
Probably my bad, there was a lot of bugs to fix when tested it on the printer and maybe forgot about this one.

**Comment by luksan47** [comment]
I agree with the general solution, let's stick with the migration.
