### ISSUE TITLE
Change tables on mobile

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#150]
The searchable tables are pretty good for PC, but almost no info is visible on mobile. We should find a way that where the backend of the current table implementation can be used, but the frontend is changed.

**Comment by katkodominik** [comment]
Do you mean the history on the printing page?
I'm not even sure if users need the function for searching in history.
Why don't we use the table the way as it is on the internet page, without the search fields?
That would solve the problem.
(And if the values inside the table are still too long, users can turn their device vertically... Not elegant, but I don't think that would be a problem.)

**Comment by luksan47** [comment]
I'm okay with turning off the search. I always use this table to check that my printing was successful.

**Comment by katkodominik** [comment]
Will be solved with #138
