### ISSUE TITLE
Change print jobs states to constants

### ISSUE THREAD

**Issue by kgerg2** [luksan47/mars#151]
https://github.com/luksan47/mars/blob/58fda7049406ae5a66013fdc45a2854127ef436a/database/migrations/2019_10_06_224327_create_print_jobs_table.php#L21
These values should be saved as constants to avoid typos similarly to [this](https://github.com/luksan47/mars/blob/master/database/migrations/2019_10_06_212436_create_mac_addresses_table.php#L22) ([discussed here](https://github.com/luksan47/mars/pull/116#discussion_r382802242)).

**Comment by steakhal** [comment]
I cannot agree more. Stronger types!
