### ISSUE TITLE
Add 'report a bug'  function (backend)

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#156]

**Comment by steakhal** [comment]
We must have this feature. Especially if we plan to work on this really actively.

Also note that it must have some spam protection mechanism, like a captcha or something.

**Comment by luksan47** [comment]
I'm okay with it, if it links to the github issues. However, it will result in hungarian issues.

**Comment by steakhal** [comment]
I think we should not redirect to Github issues directly.
We should not expect any users to click more than a few buttons on reporting a bug.

For more advanced users we could offer a link to report the issue directly.

Also, note that this feature should handle feature requests as well.

**Comment by luksan47** [comment]
Under redirect, I mean using github API. I am strongly against reinventing
the wheel as this was one of the main problems in the past with Urán 1.0.

Balazs Benics <notifications@github.com> ezt írta (időpont: 2020. febr.
24., H 15:28):

**Comment by katkodominik** [comment]
I can easily add an html tag that opens the user's default mail client with address root@eotvos.elte.hu

**Comment by luksan47** [comment]
I do not want something more complicated right now.
