### ISSUE TITLE
Add Radius password field

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#16]
Workaround until [Issue #15](https://github.com/luksan47/mars/issues/15) is fixed.
Add an option to set a 8-character long Radius server username and password with alphanumeric characters only.

Create an issue when done or migrate it to the server.

**Comment by luksan47** [comment]
Fixed in #135.

**Comment by steakhal** [comment]
I don't think we should close this issue. The mentioned #135 issue has nothing to do with passwords.
@luksan47

**Comment by luksan47** [comment]
Meant to write #110. This one added the password functionality, but the one above made it actually usable.
