### ISSUE TITLE
Supportability for locales

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#162]
Currently it's hard to follow the state of different locales, makes keeping them up to date even harder. We should somehow improve on this stage.
@uno20001, do you know of any extension that could help us?
If there is nothing, I think it would make sense to implement it as a page. This way, uran-users could translate the page themselves and we only need to review and commit them.

**Comment by katkodominik** [comment]
If we don't find any promising extension:
I was thinking about a page, where all the expressions are displayed, and if something is not translated correctly in the user's current language, they can rewrite that and generate and download the language files which they can then send to us... Or something like that. :D (idk if we could associate these with github to automatically create pr-s)

This way, we could get more collaborators, and we can even display them on this page to thank them.

Cons: we need to continuously update that page with new language expressions and someone has to manage the incoming contributions.

What do you think?

**Comment by luksan47** [comment]
I think there is an option with GitHub API to send PRs that way, the users do not even have to download files, they could just simply modify the translations and we can generate the diff from that.

This way, by generating automatic PRs and integrating it to GitHub we might save some work, and do not have to implement our own review system.

So, I think it would be a good and not too hard to implement approach.

**Comment by luksan47** [comment]
> Cons: we need to continuously update that page with new language expressions and someone has to manage the incoming contributions.

I think we can solve it automatically by saving the locales in the db.

**Comment by kdmnk** [comment]
Work on #205 first
