### ISSUE TITLE
Unable to modify internet access close to the actual date.

### ISSUE THREAD

**Issue by bondicilaszlo** [luksan47/mars#178]
On March 30th I couldn't activate the internet access which expired on the same day. Similarly, I couldn't activate those ones expired on March 15th. Outside this interval I was able to modify (activate/deactivate). See the screenshots.

![image](https://user-images.githubusercontent.com/49031938/77906451-48293400-7288-11ea-909e-04df45041d8e.png)

![image](https://user-images.githubusercontent.com/49031938/77906521-5f682180-7288-11ea-889b-5cf3d4d91a44.png)

**Comment by steakhal** [comment]
@bondicilaszlo If you think that this is a critical issue, feel free to assign the HIGH priority.

**Comment by luksan47** [comment]
I guess since almost nobody is in the Collegium, the whole project is not high priority 😞

**Comment by luksan47** [comment]
Seems like modifying the expiration date solved the issue. @bondicilaszlo could you please check?
