### ISSUE TITLE
Undefined validation messages

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#191]
Make sure that validation error messages don't use undefined (and untranslated) variables (see validation.php in language files for raw expressions - now they are displayed without substitution). (Paraphrasing without variables could be good, but not elegant and we need to do that in every language.)

**Comment by kdmnk** [comment]
To translate the input names we have to add the translations in `validation.php` under` attributes`, which we are currently planning to remove from git. The `validation.php`s should stay on git (I will keep in mind).

**Comment by luksan47** [comment]
The validation.php could be an exception for gitignore, it's already available in many languages, we should not translate again.

**Comment by kdmnk** [comment]
> The validation.php could be an exception for gitignore, it's already available in many languages, we should not translate again.

Yes, but we have to add the translations for these names manually.
