### ISSUE TITLE
Enable confirmed emails

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#198]
Since the mail client is ready, we can enable Laravel's built-in mail verification.

**Comment by kdmnk** [comment]
The verification should also be required if the users change their email address.

**Comment by kdmnk** [comment]
The problem is that the admin's registration confirmation and the user's email confirmation uses the same attribute.
We will have to separate this if we want to do this properly and we need both of the confirmations.

**Comment by luksan47** [comment]
I think the column name for verification should be customizable, we should check the docs.

**Comment by luksan47** [comment]
Hm, I could not find it, maybe it's not not easy.
I'm thinking about wether email verification is necessary... Do we really need it? Maybe we could just require a second field to make sure they do not have typo in their email. We will verify them manually anyways...

**Comment by kdmnk** [comment]
> Hm, I could not find it, maybe it's not not easy.
> I'm thinking about wether email verification is necessary... Do we really need it? Maybe we could just require a second field to make sure they do not have typo in their email. We will verify them manually anyways...

Yes, and the email address can be edited later by the user, and validating that too is another problem.

**Comment by luksan47** [comment]
> > Hm, I could not find it, maybe it's not not easy.
> > I'm thinking about wether email verification is necessary... Do we really need it? Maybe we could just require a second field to make sure they do not have typo in their email. We will verify them manually anyways...
> 
> Yes, and the email address can be edited by the user, and validating that too is another problem.

Yeah, I think the most important point of email verification is to ensure that we have no fake registrations. Since we solve it differently, I do not think this function is necessary. If someone has a wrong mail, it will be by mistake and they should contact us.
