### ISSUE TITLE
No-confirmation registration link

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#20]
There should be an option (with a fix link, link generation, or something clever, not sure) to get a link which through the users should be accepted automatically.

**Comment by michaela546** [comment]
HI I can solve this issue. Do you need to create link which will  be send on mail and will finish registration?

**Comment by luksan47** [comment]
Hi,
not quite. Here's the problem:
for students, the registration is complete, when an admin verifies that they are really a student. However, at the beginning of the semester, it's a cumbersome work, and it would be nice to have an option, which generates a link which through users can register without the process above. This should work for a customisable period of time. The link will be sent in a different mail manually (the same which tells them about the system).

**Comment by michaela546** [comment]
Hello :)

I have a few questions.

1. Do you mean that, in some time period it is possible to add roles as students? Or did I get it wrong?

2. And what type of link do you mean to send to students?

I hope that my questions are clear 💃 
Thank you very much, Michaela.

**Comment by steakhal** [comment]
@michaela546 @luksan47 
## I think the use-case would look like this:
> 1) A registration link will be sent to the verified student via a different service, we don't have to do anything about that.
> 2) In the content each of the mentioned email message, will be a link, which is generated by your service <-- it is your task.
> 3) If the student clicks on that link, opens a site where he/she can enter the credentials for his/her account to be created. This account registration should not be acknowledged by the admin, since already safe to assume that the user, who is registering is authenticated, only form values should be verified as always.
> 4) If registration completed (all validation rules are satisfied), his/her account is immediately usable, no further steps are required by any admin.

## Requirements for such *registration links*:
- Should be valid only a period of time. (eg. for a week or two)

## The main question is the following:
Should this link contain information about the user? Like his/her name?
If so, she/he should set only his/her password, which makes the UI easier, but link generation will depend on the user, so the integration into the 3rd party mailing service, you mentioned would be much harder.

## What do you think @luksan47  
Should we make link generation depend on the user, or not?

**Comment by luksan47** [comment]
@steakhal The use case is right, thanks for clarifying. 

Regarding the questions: it will be sent to a mail list, therefore it does not have to be user-specific.

**Comment by steakhal** [comment]
Here is some advice @michaela546.

I think this task has **two** subtasks.
1) Create the infrastructure, that would enable admins to manage registration links: *Issue* such link with a given deadline, *revoke* one before the deadline, *make it revoked automatically* after the deadline has reached. This could be accomplished by a token in a table: an id (unique int ID), deadline (date), and *token* (string of 64 chars?).
2) Embed this *token* into the [register blade](https://github.com/luksan47/mars/blob/master/resources/views/auth/register.blade.php) as a GET parameter, make sure that paramter is properly propagated to the [controller](https://github.com/luksan47/mars/blob/master/app/Http/Controllers/Auth/RegisterController.php#L12) which is routed by the [web.php](https://github.com/luksan47/mars/blob/master/routes/web.php#L32). Modify the controller to verify the *token*. If the token was issued and used before the deadline, handle registration as if it was automatically *verified* by the admin. For this functionality check the [RegistrationsController](https://github.com/luksan47/mars/blob/master/app/Http/Controllers/Admin/RegistrationsController.php#L19) for reference.

Not sure this database scheme for handling *registration-tokens* would fit perfectly.
I think it would be better to add a new row when the admin issues a new registration-token.
This would be the easiest for you @michaela546.
The deadline column would even prevent users from using an out-dated link to register without noticing. In such a cases the admin should approve the registration manually, as now does.

**Comment by luksan47** [comment]
Hi @michaela546, what's your status regarding this issue?

**Comment by michaela546** [comment]
Hello, I'm thinking about it and I will let you now as soon as possible. Thank you :)

**Comment by luksan47** [comment]
Hi @michaela546 are you still interested in this task? Has been any progress made?

**Comment by michaela546** [comment]
Hello, I'm working on it right now. I will let you know today or tomorrow ;)
Thank you, Michaela.

Dňa ne 27. 10. 2019, 15:32 Norbert Luksa <notifications@github.com>
napísal(a):

**Comment by michaela546** [comment]
Hello @luksan47, can you please check my pull request?

Thank you very much, Michaela.

**Comment by luksan47** [comment]
Hi @michaela546, thanks for the contribution, I will check it as soon as possible, but currently my schedule is quite busy, I'll probably have time only in the weekend.

**Comment by luksan47** [comment]
This will be a non-issue with the new admission page. Won't work this year, but we will survive this...
