### ISSUE TITLE
Move localization files to database

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#205]
...for easier handling in the future.

**Comment by uno20001** [comment]
In my humble opinion that would be a contra-productive move. Moving them into a database would cause unnecessary overhead on the database, slowing the site (there must certainly be a reason why [almost] every framework uses localization files). As far as I can tell, this came up in connection with #162, with that in mind, I would suggest that the primary source of strings for the site be the localization files. And for purposes of easing the translation process, copies of the strings could be stored in a database, where they may be edited on a dedicated page. A cron job could also be scheduled that generates the localization files from the database at certain intervals. As far as I know this is popular and prevalent way of handling this situation. This way the benefits of Laravel's built-in localization subsystem and the easy translation process could be enjoyed.

**Comment by luksan47** [comment]
Yes, this is similar to what we are planning to do here.

**Comment by luksan47** [comment]
So the goal of this issue is to:
 - move the values of the localization files to the database
 - write a script that generates the files from the db
(I do not think we should use cron jobs here, it's enough to generate after reviewing the changes.)

The goal of #162 is to create the UI based on this process.

**Comment by uno20001** [comment]
I see, however, I still think automated generation of the accepted translations is more convenient.

**Comment by luksan47** [comment]
The translation would be generated automatically, upon successful review, but not via cron jobs. I do not see why they are necessary if we exactly know when we want to run the script.

**Comment by luksan47** [comment]
BTW, thanks @uno20001 for your input, it's much appreciated.
