### ISSUE TITLE
Cannot logout with unverified user

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#210]
After registering a collegist user (but probably the same happens with tenants), I cannot log out (can't see the button).

**Comment by kdmnk** [comment]
I think it's because the route is under `Route::middleware(['auth', 'log', 'verified'])`.
Moving it outside would solve the problem? Or should we create an other middleware without the 'verified' parameter?

**Comment by luksan47** [comment]
We should create a middleware group without the verified tag.
