### ISSUE TITLE
mass mailing: sendStatementMail

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#219]
There will be cases where we will have to send a mail to every student about some notification. This could slow the site down and also mark us as spam. We will have to configure queues to avoid these issues: https://laravel.com/docs/6.x/queues

**Comment by kdmnk** [comment]
`Mail::to($user)->queue(...)` itself worked for me with the basic config. Did you mean we need further configuration?

**Comment by luksan47** [comment]
Great, thought there would be more config needed.
Now we can define SecretariatController::sendStatementMail, let's add it with this issue as an example.
