### ISSUE TITLE
Delete test accounts from release 

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#230]
In the current public release, I found these accounts:

- Vendeg Próba (Ábel)
- Test
- There are 2 Estike
- There are 2 asd
- palacsinta

If we need test accounts, we should use appropriate names.

**Comment by luksan47** [comment]
In fact, we should delete these. No test should appear in production.

**Comment by luksan47** [comment]
I did not delete the Estike accounts, I think something was configured there. Also, there was a "Rendszer" account with id 1, I was not brave enough to remove this. Rest is deleted. (Later we can review when we will see more of the users.)
