### ISSUE TITLE
Select-user improvements

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#231]
I gathered the issues regarding the select-user function
- [x] Sort names in alphabetical order
- [ ] Accent sensitivity (#175)
- [x] ~Get usernames with ajax (#202)~
- [x] Enable multiple include (#152)
- [ ] bug: in some cases, clicking on the search label doesn't work
- [x] add blank option

**Comment by luksan47** [comment]
I will have some of these done.

**Comment by luksan47** [comment]
I am not sure if getting the usernames with ajax would solve the initial problem here. The solution (depending on the use case) would be either `Model::select()` or `Model::where()`. I am not sure if that would give much benefit, maybe the select. Filtering should be used anyway where it's neceassry.

I have not seen the last bug you mentioned, so could't do much about it. :/

**Comment by luksan47** [comment]
@kdmnk regarding the bug, are there anything we have to find the root cause or to reproduce it at least?

**Comment by luksan47** [comment]
Cannot reproduce.
