### ISSUE TITLE
Add the new faculty and workshop

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#234]
Add _Gazdaságtudománytudományi Intézet_ faculty and _Gazdálkodástudományi műhely_ workshop.

**Comment by luksan47** [comment]
Note: this should be added with a separate migration, but we also have to ensure that fresh migrations won't fail/add duplicates.

**Comment by kdmnk** [comment]
> we also have to ensure that fresh migrations won't fail/add duplicates.

`->insertOrIgnore(...)` should solve that issue.

**Comment by luksan47** [comment]
This only works, if the names are set to unique (which should be the case, or if not, cane be set).
