### ISSUE TITLE
PrintHistory Table fails to load

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#281]
Error on pages with tables:
<img width="753" alt="Screenshot 2020-08-27 at 19 06 32" src="https://user-images.githubusercontent.com/17162394/91472904-6d9e8600-e898-11ea-9048-9453d505db50.png">

**Comment by luksan47** [comment]
I do not see this on the current version of the uran-2.x branch.

**Comment by kdmnk** [comment]
> I do not see this on the current version of the uran-2.x branch.

Me neither.

**Comment by luksan47** [comment]
This still happens, but only in production.

**Comment by kdmnk** [comment]
This applies only to printing history. Other tables work fine for me.

**Comment by kdmnk** [comment]
Maybe we can reproduce this on localhost as well, just we have empty printing history by default on the test environment. Not tested yet.

**Comment by luksan47** [comment]
Maybe this could be related to the logs I sent you yesterday?
`[2020-08-30 19:59:31] local.ERROR: implode(): Invalid arguments passed {"userId":188,"exception":"[object] (ErrorException(code: 0): implode(): Invalid arguments passed at /var/www/uran/app/Http/Con
trollers/PrintController.php:222)`

**Comment by luksan47** [comment]
Sent a PR  with a possible fix.
