### ISSUE TITLE
Create UI and base of the backend for import license

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#287]
Same as in the house rules, 2nd appendix.

**Comment by kdmnk** [comment]
how is this different from #286 ? Do we need a form too?

**Comment by luksan47** [comment]
This should cover the programming part, the other issue the latex document generation.

**Comment by kdmnk** [comment]
So the users could type in the things that they want to import?

**Comment by luksan47** [comment]
Yeah. The main advantage of this is that we can save the data and next year when they bring in the same laptop, mobile, etc. they won't have to find all the serial numbers and stuff.

**Comment by kdmnk** [comment]
I will make the UI for now
