### ISSUE TITLE
Mass handle registrations

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#305]
When the admin accpets/rejects a newly registered user while showing his/her data, the next user could appear.

**Comment by luksan47** [comment]
Why are we opening this? I thought after discussing under #20 that we will not support this. Or what should be done here?

**Comment by kdmnk** [comment]
I was thinking about this: https://github.com/luksan47/mars/pull/282#issuecomment-682430789
Or have you opened another issue for this?

**Comment by luksan47** [comment]
Right, I forgot this one. Okay, updated the description.
