### ISSUE TITLE
URL in the approved registration email points to localhost

### ISSUE THREAD

**Issue by mraron** [luksan47/mars#321]
Pretty much the title (I received the email with the wrong link).

I've never worked with laravel but from searching the usage of `mail.approved_registration` message I found the the file `resources/views/emails/approved_registration.blade.php` which in conjunction with the contents of `config/app.php` suggests me that the environment variable `APP_URL` is not set correctly on the production server.

**Comment by luksan47** [comment]
Whoops... Forgot this one, thanks!
@kdmnk were there any new env vars that we should set?

**Comment by luksan47** [comment]
Should be fixed now.
