### ISSUE TITLE
Printing backend: create free page handler function

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#33]
Implement a function which modifies a users's free page settings in the PrintController class.

**Comment by boldar99** [comment]
Should it be a simple setter method, or some of incrementing / decrementing function?

**Comment by luksan47** [comment]
It should be a simple increment method for the pages (you can use Laravel's increment() function), and a similar update for the date (when will the free pages expire).

**Comment by steakhal** [comment]
Is this related to #26 and #64? @luksan47 
Should we update the Kanban table appropriately?

**Comment by luksan47** [comment]
Yes, this issue was duplicated.
Now let's just close them and only keep one for the project.

**Comment by luksan47** [comment]
@steakhal's #64 solves this issue.
