### ISSUE TITLE
Docker for unified development environment

### ISSUE THREAD

**Issue by steakhal** [luksan47/mars#34]
For easier setup and dependency management it would be valuable to use some **Docker** functionalities.

**Goal**: after cloning this repository the developer could get the *mars* site working on his/her local machine using only **one** command, like `docker-compose up -d`.

**Add documentation**: write a developer guide.

**Might useful**:
- [docker compose](https://docs.docker.com/compose)
- [blog](https://dev.to/aschmelyun/the-beauty-of-docker-for-local-laravel-development-13c0)
- [youtube video](https://www.youtube.com/watch?v=0HTruhilvcU)
- [github example](https://github.com/aschmelyun/docker-compose-laravel)

**Comment by luksan47** [comment]
Note: for OS X users [Valet](https://laravel.com/docs/6.x/valet) provides easy-to-set-up and smooth development experience.
For Windows/Linux users, [Laravel Homestead](https://laravel.com/docs/6.x/homestead) is an official alternative. From the documentation: 

>  Vagrant provides a simple, elegant way to manage and provision Virtual Machines. Homestead is an official, pre-packaged Vagrant box that provides you a wonderful development environment without requiring you to install PHP, a web server, and any other server software on your local machine.

Installation and configuration guideline can be found on the linked documentation.

**Comment by vendi95** [comment]
Because the Vagrant based solution is officially supported we use that for now. See #53.

**Comment by luksan47** [comment]
If it comes to reopening this issue, this page will be helpful:
https://dev.to/aschmelyun/the-beauty-of-docker-for-local-laravel-development-13c0
