### ISSUE TITLE
Undefined index for config.locale

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#341]
This line (found in localizations.blade, but could be elsewhere as well)
`{{ config('app.locales')[App::getLocale()] }}`
causes
`ErrorException
Undefined index: (View: /Users/norbertluksa/mars/resources/views/localizations.blade.php)`
if a language is not selected beforehand.

**Comment by mraron** [comment]
How do I exactly reproduce this? I tried to `App:setLocale("")` but it doesn't work, do I have to manually set the locale cookie or smth else?

**Comment by luksan47** [comment]
Not sure what was the problem here, I found this entry in the server logs. Now I checked the logs from last month and it seems to be gone, so closing this issue.
