### ISSUE TITLE
Edit all user attributes

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#365]
This way, the secretariat and the user him/herself could be able to change (some) of the attributes, not just the administrators.

**Comment by domonkos2001** [comment]
Hello, can i work on this issue?

**Comment by kdmnk** [comment]
Hi! Sure! Right now, the users can change their email address and mobile number only. For now, extending these to other personal data should be enough. This includes modifying the blades with adding JavaScript and ajax requests, and creating new handler functions in the controllers. All of this can be copied from the existing ones. Feel free to ask if you don't find something!
