### ISSUE TITLE
Change code style

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#37]
Change the default coding style from
```
fun
{
}
```
like braces to
```
fun {
}
```

**Comment by luksan47** [comment]
Or am I the only one bother by it?

**Comment by steakhal** [comment]
No, I also prefer the shorter form.

You can experiment with the different coding styles in the PhpStorm under the following sections:
ALT + CTRL + S => settings window.

`Settings/Editor/Code Style/PHP/Default Scheme/Wrapping and Braces/Braces placement/In function declaration` set to `End of line`.

![image](https://user-images.githubusercontent.com/6280485/66417541-7bd58080-ea00-11e9-971b-2104f1dbe078.png)

**Comment by steakhal** [comment]
Also note that you can use the `ALT + CTRL + L` to reformat the whole opened file.

**Comment by steakhal** [comment]
@luksan47  What should be the naming convention for variable names?
If not [snake_case](https://en.wikipedia.org/wiki/Snake_case) than [camelCase](https://en.wikipedia.org/wiki/Camel_case)?
How should we accomplish the transition from one style to the other?

**Comment by luksan47** [comment]
We could follow Laravel's style everywhere, maybe they also made some convention document? Could someone do the research here.

> How should we accomplish the transition from one style to the other?

I'm afraid we cannot do it without a proper code freeze, and to avoid a tons of merge conflicts, the best time would be at the release.

**Comment by steakhal** [comment]
I agree.

**Comment by steakhal** [comment]
This might be useful: https://github.com/michaeldyrynda/phpstorm-laravel-code-style

**Comment by luksan47** [comment]
As I saw, Laravel follows the [PSR-2](https://laravel.com/docs/6.x/contributions#coding-style) standard with some differences. I configured styleci.io to send PRs to fix the style differences on demand. If we find it good, we can automate it.

**Comment by luksan47** [comment]
Generated #140, @steakhal what do you think?

**Comment by steakhal** [comment]
Any automation and enforcement would have a huge impact - which is what we want.

Though, I think we should not accept any PRs if that is not autoformatted.
Maybe a Github action could help automatically format and commit the changes to the PR.
So we could review the clean and auto-formatted code.

Maybe this link is helpful in achieving such:
https://github.com/stefanzweifel/laravel-github-actions-demo/tree/master/.github/workflows

**Comment by luksan47** [comment]
I think with a guideline set, we can require now the PRs to have proper style (and would allow one to set it up in their editor).
The automatic checks to pass can be a requirement of the merge, which would enforce the syle.

**Comment by steakhal** [comment]
If it were automatic, that would be awesome.
Like the CI would push an autoformat commit to the PRs branch.

On the master branch after the merge, we would see only a single commit which is perfectly formatted. Yes, I'm implying that we should not allow 'merge commits', and only use **squash** merge for PRs.

**Comment by luksan47** [comment]
We only use squash and merge now, it is enforced, that would not change.
So to sum up, our options are (that I'm okay with):

- Run automatic tests on each PR to check the style and let the developer fix.
- Same as above, but also send a style fix commit onto the same branch. This is still all automatic.
- Create automatic PRs to fix the style. I think this would result in too many PRs though.

I would go with the second option, which would mean the most automation and the least amount of extra PRs and work.

If you agree, I can turn it on.

**Comment by steakhal** [comment]
Definitely the second. All the others are nogo.

**Comment by luksan47** [comment]
All right, I'll turn it on.

**Comment by luksan47** [comment]
My plan is:

1. Close as many PRs as possible within this release cycle.
2. Open an automatic PR to fix the style globally.
3. Turn on the automatic style commits.

That way I hope it will give the least trouble and will be the smoothest.

**Comment by steakhal** [comment]
OK, but note that that formatting commit will pretty much destroy the blame. I'm still convinced that the benefit would overweight the drawback.
