### ISSUE TITLE
Already approved registrations can be seen

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#373]
Eg.
![image](https://user-images.githubusercontent.com/56202545/93305364-b0e87680-f7fe-11ea-8ff1-4942d259ac4f.png)

**Comment by luksan47** [comment]
The request should fail in this case.

**Comment by kdmnk** [comment]
We can redirect to the registrations list page in this case
________________________________

**Comment by luksan47** [comment]
Hm, yeah, that sounds better.
