### ISSUE TITLE
413 error when print ing large files

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#376]
To 1.2 MB limit does not work, the page returns with 413 payload too large.

**Comment by luksan47** [comment]
I thought 10MB was the limit?

**Comment by kdmnk** [comment]
I don't know, the page says 1.2 MB. Why is it limited anyways?
________________________________

**Comment by luksan47** [comment]
Without limit, we could run out of space easily.

Katkó Dominik <notifications@github.com> ezt írta (időpont: 2020. szept.
22., K, 10:57):

**Comment by kdmnk** [comment]
But can't we delete the file immediately after printing?

**Comment by luksan47** [comment]
We could, but currently it's done only daily.

**Comment by luksan47** [comment]
And even with deleting it right now, it's not safe to allow unlimited file size.

**Comment by luksan47** [comment]
Raised the max file size to 5GB. Also added an env var, `PRINT_MAX_FILE_SIZE` so we can change it if we have to.
