### ISSUE TITLE
Use cookies?

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#38]
There might be some scenarios where it would be comfortable for the users that we use cookies there (e.g. login). We should analyse the possibilities and add it where it makes sense.

**Comment by luksan47** [comment]
Locale could also be stored as a cookie.

**Comment by steakhal** [comment]
I'm not sure if anything else could benefit from cookies. Any idea @vendi95?

**Comment by vendi95** [comment]
The standard Laravel authentication, which we use, already uses a cookie for the remember me feature.
It would be nice to store the preferred language as a cookie, or in the DB for the user.

**Comment by luksan47** [comment]
I'm not too familiar with requirements regarding cookies, but then should not be a pop-up asking for the user's permission?

**Comment by uno20001** [comment]
I am quite certain that even without the *Remember me* feature, Laravel uses cookies, or some kind of local storage. There are Laravel packages which display a message about the use of cookies, for example [here](https://github.com/spatie/laravel-cookie-consent). This practice is only required by EU law, which, I think, explains why nothing shows up by default.

**Comment by luksan47** [comment]
Thanks @uno20001 for the input, this means we should add that message.
