### ISSUE TITLE
Add fields to registration page.

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#409]
- Extern/resident
- educational email (#377 needed)

**Comment by SayedSajadHosseini** [comment]
hey, can I work on this?

**Comment by luksan47** [comment]
Hi @SayedSajadHosseini 
sure, thanks, added you to the issue. Please place these input next to the other educational data following the design there.
The students' status: extern/resident should be a select, and the educational email should be an email field, but with different name and id from the personal email.

If you want, you could also attach the extern/resident status as a pivot to the COLLEGIST role during registration handling.

**Comment by luksan47** [comment]
Hey @SayedSajadHosseini, could you give an ETA? Thanks!

**Comment by SayedSajadHosseini** [comment]
Hey, yes of course tomorrow will finish.

**Comment by luksan47** [comment]
Sorry, I had to close the PR and took over since we got no response and have already missed a release.
