### ISSUE TITLE
Add 'print paper ran out' button

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#411]
The button would send an email to the administrators.

Or, can we track the printer status with some script?

**Comment by luksan47** [comment]
Not sure if we can get this information. What we can get is if the printer is idle, has queued jobs, is disabled, or is accepting requests.
Not sure if the last status is set when the paper runs out, has to be checked. 
If it's not the case, a long queue could indicate some problems with the printer, including paper shortage.

**Comment by luksan47** [comment]
Ah, I see the simpler option now, okay. To sum up:
if the user notices that the printer has no paper, or is about to run out, he or she could press this button that would send an email to all user with INTERNET_ADMIN rights.

**Comment by LukaSK351** [comment]
Hi, so, can you assign me here? :)

**Comment by kdmnk** [comment]
Hi! Feel free to ask questions if you get stuck.
