### ISSUE TITLE
Add notifications to navbar elements

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#413]
For example a number could be added to the registration handling line when there are new registrations.

**Comment by kdmnk** [comment]
We can use badges: https://materializecss.com/badges.html
I think this needs an ajax request placed in the navbar, and a function that returns the wanted resources' number.

**Comment by luksan47** [comment]
Yes, I was thinking about the same for the UI!

I also agree we should use AJAX. But how about sending multiple requests to the corresponding controller?

**Comment by kdmnk** [comment]
Do you mean that we should get all the data in one request?

**Comment by luksan47** [comment]
The opposite, I thought you suggested that. 😄

**Comment by kdmnk** [comment]
I don't know which is better so use multiple requests if you want that.

**Comment by luksan47** [comment]
I think multiple request is better since you want to get the Faults from the FaultController, the new registrations from the RegistrationController, etc instead of mixing them all at one place.
