### ISSUE TITLE
Check Tabulator settings for mobile display

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#414]
For example, set minimum width for the coloumns and make it scrollable (if it is not set yet).
Example:
![image](https://user-images.githubusercontent.com/56202545/95319732-a159cc00-0898-11eb-9937-1519d9feebec.png)

**Comment by luksan47** [comment]
We should try out responsive layout: http://tabulator.info/docs/4.1/layout#responsive

**Comment by luksan47** [comment]
Checked it out, we can either hide the columns that do not fit (and give priority what to hide and what not), or we move them to a second row for the same record.

<img width="513" alt="Screenshot 2020-10-09 at 21 17 42" src="https://user-images.githubusercontent.com/17162394/95623015-e175a600-0a74-11eb-8457-317bcb18b756.png">

**Comment by luksan47** [comment]
I'm not a big fun of either.

**Comment by kdmnk** [comment]
But the coloumns can be resized manually, can't we set a minimum width for them?
That should be enough, since these tables are scrollable horizontally.

**Comment by kdmnk** [comment]
For materialize tables, we can add `display: block;overflow-x:auto;` to make them scrollable. We can fix them in this issue as well.
