### ISSUE TITLE
Make admin checkout visible for collegists

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#472]
IMO, it should be. What do you think?
@kdmnk @machiato32

**Comment by kdmnk** [comment]
I'm not against it.

**Comment by kdmnk** [comment]
If the other one is visible, this should be also.

**Comment by luksan47** [comment]
I would keep this as a separate item in the navbar. Once we have 3 network related page, we can group them like we have for Secretary or Admin pages.
This should be a simple fix, the list should be separated to its own blade template then included for the user page. Maybe we already have the policies set up as well.
