### ISSUE TITLE
Automatically enable internet access for guests

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#555]
Guests should be able to use the internet (for 6 months?) after registration

**Comment by luksan47** [comment]
Rather until max(planned departure, X months). I think we now request this value at registration.

**Comment by kdmnk** [comment]
> I think we now request this value at registration.

No, we don't. But that should be better, I agree.

**Comment by luksan47** [comment]
Isn't there a PR for this? I think I've seen some work around that? (the registration page)

**Comment by machiato32** [comment]
Well I guess now it's done anyway
