### ISSUE TITLE
Fix fault report email typo

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#589]
"Egy hibát újra lett nyitva."

**Comment by kdmnk** [comment]
@luksan47 It still displays reopened fault text instead of new fault text here: https://github.com/luksan47/mars/pull/625/files#diff-abe11828c56ba5af7d9d8ed38542462efbf0a7ccc14ab61bffcdb3e3152f7039L4-R4

**Comment by luksan47** [comment]
Oh, right, because the condition is reversed...
