### ISSUE TITLE
Do not send multiple emails

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#609]
Now the system loops through certain roles and sends emails to the users with those roles.
If I have multiple roles, there are situations that I get multiple emails of the same content.
Try to find a solution for this.

**Comment by luksan47** [comment]
bcc? :)

**Comment by kdmnk** [comment]
I mean if I have secretariat and admin role at the same time, I receive two emails separately if a new user has been registered.
________________________________

**Comment by luksan47** [comment]
Yeah, instead of looping through the users and sending them each a mail, let's just collect the users in a bcc list and send at once.

**Comment by luksan47** [comment]
This is not an issue on the uran-2.x branch.
However I checked a few things:
 - the server has different changes that cause this behaviour.
 - master is not equivalent to the version on the server.

The violation of the above two is ill-advised and can cause a lot of trouble (like this). I strongly suggest not developing anything on the server, but if something goes in, it should be pushed to master first, and then merged to uran-2.x.

**Comment by luksan47** [comment]
Now that I see it's updated, I'll create a quick fix.
