### ISSUE TITLE
Refactor PrintController::modify_balance

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#65]
Follow the same logic with modify_free_pages.
Also, we should agree in the naming convention. For PHP, it's as we use it, but for Laravel, it's camelCase.

**Comment by steakhal** [comment]
So which convention should we follow?

**Comment by luksan47** [comment]
I would go with Laravel's for functions, as they are an interconnection of the system. For the variables, maybe stay with the PHP convention, as they are more local.
@vendi95 what do you think?

**Comment by steakhal** [comment]
Continue the discussion on #37
