### ISSUE TITLE
Create a searchable user selector

### ISSUE THREAD

**Issue by vendi95** [luksan47/mars#68]
It is not too user-friendly to select users by id like here:
https://github.com/luksan47/mars/blob/f14789af9f2d3f2ed1ab84fc4ec7ff871a82d14c/resources/views/print/modify.blade.php#L16

Make a reusable user selector with search functionality. (No ajax needed, the full list can be in the output.) Something like [bootstrap-select live-search](https://developer.snapappointments.com/bootstrap-select/examples/#live-search).

**Comment by steakhal** [comment]
Should we consider using some sort of fuzzy search?

**Comment by vendi95** [comment]
> Should we consider using some sort of fuzzy search?

If it is already implemented and depends only on the configuration of the used library than we can, otherwise I do not see it necessary at this stage.

**Comment by luksan47** [comment]
I agree with @vendi95, only add it if it's implemented, keep it minimal (but comfortable) for now.
We can open an issue later.

**Comment by steakhal** [comment]
Here we go.
```css
.bootstrap-select > select.bs-select-hidden, select.bs-select-hidden, select.selectpicker {
    display: none !important;
}
```

The select element is there, but hidden. Some CSS magic marks it `display: none !important`, which is sad in this case. We have to find a solution to style it properly.

A few other comments/questions to the [searchuser_print](https://github.com/luksan47/mars/commit/1ade2e8d1176e7231b8c9e905af478012dd82c1e#diff-51a86a97a1bba69216bf86fd3c3397daR2) branch.
- Should we depend on an external source for `bootstrap-select.js` or should we serve it as well?
- Why do you need the `data-token` field for each option in the selectpicker?
- If we use depend on an external source to provide the `bootstrap-select.js`, why we copy-paste the whole `bootstrap-select` with its unittests etc.
If we would require anything, we could simple copy the `bootstrap-select.js` and the corresponding `.css` file.

**Comment by steakhal** [comment]
As a solution to clean up this commit-branch, I would omit the utility-bootstrap-select folder, forcepush the *same* commit, than open a `draft pull request` for this change. We could continue the discussion there.

**Comment by katkodominik** [comment]
@steakhal 
I just pasted the data token field from the examples, i haven't tried what's the best options for the search itself.
The bootstrap-select directory is not part of that, i already deleted that from my local files, sorry :D

**Comment by vendi95** [comment]
I think that we need the display: hidden. CSS hides the element so that the bootstrap-select.js can create the rich interface in its place.
I did not have the time to see the details, but I think you are missing the js part of the library. You should put the static, minified version in the /public directory and reference it in the view (in layouts/app.blade.php now, we will fix it later). You can see an example in PR #66 that includes the tabulator js library.
