### ISSUE TITLE
Add email client

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#8]
It should be possible to send emails (to confirm registration, send important notifications, password change requests, etc.). For that, we need to come up with some solution. See config.mail.

**Comment by retep36** [comment]
Hi, can you add me to the project? I 'd like to solve this issue.

**Comment by luksan47** [comment]
Hi, thanks for the help.
First we need to send an email upon registration (no email confirmation needed), and when an admin confirms the registration (on the admin tab). Also, password change emails would be nice.
If you have questions, feel free to ask.

**Comment by luksan47** [comment]
Hi, what's your status regarding this issue?

**Comment by luksan47** [comment]
Password reminders are set by Laravel. Since this one is the most important for the release, I'll lower the priority of this issue by removing it from the Release 2.0 project.
Later, when more functionalities are out, we might consider some notifications for them (e.g. reminder about the internet expiration date). Also, it will be a must do for the Secretariat module. Feel free to share your ideas here, where would it worth it to send emails.

**Comment by luksan47** [comment]
Looks like here the hardest part here is configuring. @hamaren2517 let's discuss it offline.
