### ISSUE TITLE
Webpage integration: description of workshops

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#80]
Add a field where a workshop administrator could edit the description of their workshop's webpage.

Optional: formatting.
Alternative: unified format, fillable slots.

In case you have no sysadmin permission, open an issue for integration.

**Comment by husar** [comment]
Hello, maybe i can solve this issue, can you give me more information about this?

**Comment by rindy22** [comment]
Hello, i would like to work on this issue if it is still open. Can you tell me more informations about that issue.

**Comment by luksan47** [comment]
This porject currently needs more planning, until it's on hold. Feel free to pick another issue.
