### ISSUE TITLE
Add hungarian translation for the cookie consent pop-up

### ISSUE THREAD

**Issue by vendi95** [luksan47/mars#82]
PR #75 added a cookie consent pop-up using the *Cookie Consent by Osano* lib.
Currently, the solution is English only. We need Hungarian translation.

**Comment by luksan47** [comment]
The localization should be working, I remember adding it. (Maybe I haven't pushed?)

**Comment by luksan47** [comment]
The translation is up and running, merged in with the PR.
Closing this as non-issue.
