### ISSUE TITLE
Dropdown menus are broken/fix scripts

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#90]
Fix them.

**Comment by luksan47** [comment]
After a little triage, I found out that the issue is cause by including `js/bootstrap.min.js`, probably at the wrong place. However, removing this line would break live-search. The proper include order should be found.

Also, most of the scripts should be at the bottom, so the loading time is minimised.

**Comment by steakhal** [comment]
I can also confirm this bug, though can't offer any solution right now.
