### ISSUE TITLE
Make it possible to transfer money between users' print accounts.

### ISSUE THREAD

**Issue by katkodominik** [luksan47/mars#94]
Every user should have a field where they can choose someone to send some money from their print accounts.

**Comment by luksan47** [comment]
Not a must do for the release, but a nice to have feature.

**Comment by luksan47** [comment]
I've been thinking about this idea. It's great, but wouldn't a lending system be even better? That way the lender will get his money back once his/her partner pays up.

**Comment by luksan47** [comment]
What do you think?

**Comment by steakhal** [comment]
I also think it is lowprio, but keep it on the roadmap.
For the lending, I think a single checkbox could turn the 'send' to 'lend' :D But would be an awesome feature for sure.

**Comment by luksan47** [comment]
@katkodominik what do you think, is it possible to finish the PR for the end of the month?

**Comment by katkodominik** [comment]
@luksan47 It is working already (see #131).
If we want to send money to someone's free pages, i need  #149 included.

**Comment by luksan47** [comment]
I am working on #149, will include soon.
I am thinking about adding a comment column to the free pages they can be tracked why the user got it. Lending could use this column as well.

**Comment by luksan47** [comment]
Just realised that the problem with free pages sent as balance is that we have no universal cost for a page. It can differ when one or two sided printing is used. So maybe we can stick with the current solution (unless we want to complicate free pages to one-sides-free, two-sided-free).
