### ISSUE TITLE
Change free pages system

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#97]
Currently, a user can have `n` free pages, with a deadline.
Change it so the user can have different amounts of free pages with different deadline. They should be all listed for the user and print admins should be able to revoke them.

**Comment by steakhal** [comment]
I'm not sure if we really need this. Why don't want we keep it simple?
Could you give some real world use-cases?

**Comment by luksan47** [comment]
A use case would be:
 * teacher have free pages to print, so they have n pages for a semester
 * someone could be asked to print some posters for a conference, thus given m pages for the week
 * if they are the same person, there could be some conflicts with the set date or the added money.

It might be just some edge-case, and I do not insist adding it. @vendi95, what do you think?
